##included:
##    - Source
disabled_rules: # rule identifiers to exclude from running
  - colon
  - line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Source/Debug+Preview.swift
